name: calcolatrice
description: smart contract per effettuare le 4 operazioni aritmetiche
events: {}
structs: {}
typedefs: {}
state:
    owner: AgentID # current owner of this smart contract
    res: Int64
funcs:
    init:
        params:
            owner: AgentID? # optional owner of this smart contract
    setOwner:
        access: owner # current owner of this smart contract
        params:
            owner: AgentID # new owner of this smart contract
    add:
        access: owner
        params:
            number1: Int64
            number2: Int64
    subtract:
        access: owner
        params:
            number1: Int64
            number2: Int64
    multiply:
        access: owner
        params:
            number1: Int64
            number2: Int64
    divide:
        access: owner
        params:
            number1: Int64
            number2: Int64
views:
    getOwner:
        results:
            owner: AgentID # current owner of this smart contract
    getRes:
        results:
            res: Int64
