// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

package calcolatrice

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

const (
	ScName        = "calcolatrice"
	ScDescription = "smart contract per effettuare le 4 operazioni aritmetiche"
	HScName       = wasmtypes.ScHname(0x6c6e8c95)
)

const (
	ParamNumber1 = "number1"
	ParamNumber2 = "number2"
	ParamOwner   = "owner"
)

const (
	ResultOwner = "owner"
	ResultRes   = "res"
)

const (
	StateOwner = "owner"
	StateRes   = "res"
)

const (
	FuncAdd      = "add"
	FuncDivide   = "divide"
	FuncInit     = "init"
	FuncMultiply = "multiply"
	FuncSetOwner = "setOwner"
	FuncSubtract = "subtract"
	ViewGetOwner = "getOwner"
	ViewGetRes   = "getRes"
)

const (
	HFuncAdd      = wasmtypes.ScHname(0xa90e054b)
	HFuncDivide   = wasmtypes.ScHname(0xc7878107)
	HFuncInit     = wasmtypes.ScHname(0x1f44d644)
	HFuncMultiply = wasmtypes.ScHname(0x7a5e842c)
	HFuncSetOwner = wasmtypes.ScHname(0x2a15fe7b)
	HFuncSubtract = wasmtypes.ScHname(0xc6ab6901)
	HViewGetOwner = wasmtypes.ScHname(0x137107a6)
	HViewGetRes   = wasmtypes.ScHname(0x3848b097)
)
