// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

package calcolatrice

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type ImmutablecalcolatriceState struct {
	proxy wasmtypes.Proxy
}

// current owner of this smart contract
func (s ImmutablecalcolatriceState) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(StateOwner))
}

func (s ImmutablecalcolatriceState) Res() wasmtypes.ScImmutableInt64 {
	return wasmtypes.NewScImmutableInt64(s.proxy.Root(StateRes))
}

type MutablecalcolatriceState struct {
	proxy wasmtypes.Proxy
}

func (s MutablecalcolatriceState) AsImmutable() ImmutablecalcolatriceState {
	return ImmutablecalcolatriceState(s)
}

// current owner of this smart contract
func (s MutablecalcolatriceState) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(StateOwner))
}

func (s MutablecalcolatriceState) Res() wasmtypes.ScMutableInt64 {
	return wasmtypes.NewScMutableInt64(s.proxy.Root(StateRes))
}
